### ISSUE TITLE
[feature-request] Automatically takes Track, Artist and Album Name from audio file

### ISSUE THREAD

**Issue by skj-skj** [iiPythonx/lrcup#2]
audio files contain various metadata which includes Track, Artist and Album Name.

it will be a quality of life feature to have if it automatically takes the values from the audio file if available.

**Comment by iiPythonx** [comment]
Added in 0be08ba6cd3b6c176f0b5842ca1c30bbe140e6a6, published in 0.5.1.  
If you have any other suggestions for it, feel free to let me know.
