### ISSUE TITLE
Artifacts in lyrics after uploading

### ISSUE THREAD

**Issue by aayushnatar** [iiPythonx/lrcup#5]
![Screenshot 2024-09-27 at 22-34-12 LRCLIB](https://github.com/user-attachments/assets/8b18228a-e5ad-46f1-9f16-45acce4ae063)
(how it is on lrclib)
![Screenshot 2024-09-27 223636](https://github.com/user-attachments/assets/a07bab16-ec0b-4d4b-83c8-4634a3ce4a15)
(how it actually is)

**Comment by aayushnatar** [comment]
Seems to only happen on the ‘ character

**Comment by iiPythonx** [comment]
I'm not able to reproduce this, sending lyrics with `‘` via LRCup and LRCGET both seem to work fine and renders properly.

**Comment by iiPythonx** [comment]
Actually, I've pushed a possible fix (assuming you're on Windows), please upgrade from git (or wait for the PyPI release) and let me know if it's still broken.

**Comment by Diowboss** [comment]
I will test it in a few hours!

**Comment by aayushnatar** [comment]
can confirm that fix does work
![Screenshot 2024-09-28 at 18-59-14 LRCLIB](https://github.com/user-attachments/assets/530fdb67-d6bb-4a41-8efc-035048496a6a)
