### ISSUE TITLE
[feature-request] support for '.m4a' file for uploading synced lyrics

### ISSUE THREAD

**Issue by skj-skj** [iiPythonx/lrcup#6]
Please add support for '.m4a' audio files for uploading synced lyrics

**Comment by iiPythonx** [comment]
Might take some time, m4a is a completely different format that I would have to account for. I'll work on it and see what I can do.

**Comment by skj-skj** [comment]
Hi @iiPythonx, if its okay I would like to implement this feature and contribute to the project. please let me know.
